### ISSUE TITLE
Release/version mismatch

### ISSUE THREAD

**Issue by fabaff** [xuanxuan000/python-linknlink#2]
There is a mismatch between the releases and the code:

- PyPI: 0.2.0, https://pypi.org/project/linknlink/0.2.0/
- GitHub: 0.1.9, https://github.com/xuanxuan000/python-linknlink/releases/tag/0.1.9

`setup.py` in `main` says [1.9.0](https://github.com/xuanxuan000/python-linknlink/blob/main/setup.py#L8).

**Comment by xuanxuan000** [comment]
sorry, It was a mistake. I've already removed it.
